version: "3.9"

networks:
  default:
    name: instill-network

volumes:
  conenctor_config:
    name: connector-config
  conda_pack:
    name: conda-pack
  model_repository:
    name: model-repository

services:
  mgmt_backend_migrate:
    container_name: mgmt-backend-migrate
    image: instill/mgmt-backend:${MGMT_BACKEND_VERSION}
    restart: on-failure
    environment:
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
    entrypoint: ./mgmt-backend-migrate
    depends_on:
      pg_sql:
        condition: service_healthy

  mgmt_backend_init:
    container_name: mgmt-backend-init
    image: instill/mgmt-backend:${MGMT_BACKEND_VERSION}
    restart: on-failure
    environment:
      CFG_SERVER_PORT: 8080
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
    entrypoint: ./mgmt-backend-init
    depends_on:
      - mgmt_backend_migrate

  mgmt_backend:
    container_name: mgmt-backend
    image: instill/mgmt-backend:${MGMT_BACKEND_VERSION}
    restart: unless-stopped
    environment:
      CFG_SERVER_PORT: 8080
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
    ports:
      - 8080:8080
    depends_on:
      - mgmt_backend_init

  pipeline_backend_migrate:
    container_name: pipeline-backend-migrate
    image: instill/pipeline-backend:${PIPELINE_BACKEND_VERSION}
    restart: on-failure
    environment:
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
    entrypoint: ./pipeline-backend-migrate
    depends_on:
      pg_sql:
        condition: service_healthy

  pipeline_backend:
    container_name: pipeline-backend
    image: instill/pipeline-backend:${PIPELINE_BACKEND_VERSION}
    restart: unless-stopped
    environment:
      CFG_SERVER_PORT: 8081
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
      CFG_MGMTBACKEND_HOST: mgmt_backend
      CFG_MGMTBACKEND_PORT: 8080
      CFG_CONNECTORBACKEND_HOST: connector_backend
      CFG_CONNECTORBACKEND_PORT: 8082
      CFG_MODELBACKEND_HOST: model_backend
      CFG_MODELBACKEND_PORT: 8083
      CFG_TEMPORAL_CLIENTOPTIONS_HOSTPORT: "temporal:7233"
    ports:
      - 8081:8081
    depends_on:
      - pipeline_backend_migrate
      - mgmt_backend
      - connector_backend
      - model_backend
      - temporal
      - redis

  connector_backend_migrate:
    container_name: connector-backend-migrate
    image: instill/connector-backend:${CONNECTOR_BACKEND_VERSION}
    restart: on-failure
    environment:
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
    entrypoint: ./connector-backend-migrate
    depends_on:
      pg_sql:
        condition: service_healthy

  connector_backend_init:
    container_name: connector-backend-init
    image: instill/connector-backend:${CONNECTOR_BACKEND_VERSION}
    restart: on-failure
    environment:
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
    entrypoint: ./connector-backend-init
    depends_on:
      - connector_backend_migrate

  connector_backend_worker:
    container_name: connector-backend-worker
    image: instill/connector-backend:${CONNECTOR_BACKEND_VERSION}
    restart: unless-stopped
    environment:
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
      CFG_TEMPORAL_CLIENTOPTIONS_HOSTPORT: temporal:7233
    volumes:
      - conenctor_config:/connector-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ./connector-backend-worker
    depends_on:
      - connector_backend_init
      - temporal

  connector_backend:
    container_name: connector-backend
    image: instill/connector-backend:${CONNECTOR_BACKEND_VERSION}
    restart: unless-stopped
    environment:
      CFG_SERVER_PORT: 8082
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
      CFG_MGMTBACKEND_HOST: mgmt_backend
      CFG_MGMTBACKEND_PORT: 8080
      CFG_TEMPORAL_CLIENTOPTIONS_HOSTPORT: temporal:7233
      CFG_SERVER_CORSORIGINS: http://localhost:3000
    ports:
      - 8082:8082
    depends_on:
      - connector_backend_init
      - mgmt_backend

  model_backend_migrate:
    container_name: model-backend-migrate
    image: instill/model-backend:${MODEL_BACKEND_VERSION}
    restart: on-failure
    environment:
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
    entrypoint: ./model-backend-migrate
    depends_on:
      pg_sql:
        condition: service_healthy

  model_backend_init:
    container_name: model-backend-init
    image: instill/model-backend:${MODEL_BACKEND_VERSION}
    restart: on-failure
    environment:
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
    entrypoint: ./model-backend-init
    depends_on:
      - model_backend_migrate

  model_backend:
    container_name: model-backend
    image: instill/model-backend:${MODEL_BACKEND_VERSION}
    restart: unless-stopped
    environment:
      CFG_SERVER_PORT: 8083
      CFG_DATABASE_HOST: pg_sql
      CFG_DATABASE_PORT: 5432
      CFG_DATABASE_USERNAME: postgres
      CFG_DATABASE_PASSWORD: password
      CFG_TRITONSERVER_GRPCURI: triton-server:8001
      CFG_TRITONSERVER_MODELSTORE: /model-repository
    ports:
      - 8083:8083
    volumes:
      - model_repository:/model-repository
    depends_on:
      triton_server:
        condition: service_healthy
      model_backend_init:
        condition: service_completed_successfully

  triton_conda_env:
    container_name: triton-conda-env
    image: instill/triton-conda-env:${TRITON_CONDA_ENV_VERSOIN}-cpu
    volumes:
      - conda_pack:/conda-pack

  triton_server:
    container_name: triton-server
    image: ${TRITONSERVER_IMAGE_TAG}
    restart: unless-stopped
    command: tritonserver --model-store=/model-repository --model-control-mode=explicit --allow-http=true --strict-model-config=false
    ports:
      - 8001:8001
    volumes:
      - model_repository:/model-repository
      - conda_pack:/conda-pack
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/v2/health/ready"]
      timeout: 20s
      retries: 10
    shm_size: 2gb
    ulimits:
      memlock: -1
      stack: 67108864
    depends_on:
      - triton_conda_env

  pg_sql:
    container_name: pg-sql
    image: postgres:${POSTGRESQL_VERSION}-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    restart: unless-stopped
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=pg_sql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    ports:
      - 7233:7233
    depends_on:
      pg_sql:
        condition: service_healthy

  temporal_admin_tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    restart: unless-stopped
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true
    depends_on:
      - temporal

  temporal_ui:
    container_name: temporal-ui
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - 8088:8080
    depends_on:
      - temporal

  redis:
    container_name: redis
    image: bitnami/redis:6.2.6-debian-10-r34
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  redoc_openapi:
    container_name: redoc-openapi
    image: redocly/redoc:v2.0.0-rc.70
    environment:
      - SPEC_URL=https://raw.githubusercontent.com/instill-ai/protobufs/main/openapiv2/openapiv2.swagger.yaml
    ports:
      - 3001:80

  frontend:
    container_name: instill-console
    stdin_open: true
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
