version: "3.9"
services:
  develop:
    container_name: instill-console
    stdin_open: true
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISABLE_USAGE_COLLECTION=false
      - MGMT_BACKEND_BASE_URL=http://localhost:8084
      - PIPELINE_BACKEND_BASE_URL=http://localhost:8081
      - CONNECTOR_BACKEND_BASE_URL=http://localhost:8082
      - MODEL_BACKEND_BASE_URL=http://localhost:8083
      - CONSOLE_DOMAIN=localhost
      - API_VERSION=v1alpha
      - CONSOLE_EDITION=local:ce-dev
