packages:
  - "packages/*"
  - "apps/*"
  - "toolings/*"

catalog:
  "@tanstack/react-query": ^5.59.15
  "@types/node": "^20.17.7"
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8
