packages:
  - "packages/*"
  - "apps/*"
  - "toolings/*"

catalog:
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.8.3
  tsup: "^8.3.5"
  react: "^18.3.1"
  tsx: "^4.19.4"
  next: "^15.4.7"
  zod: "^3.25.56"
  postcss: "^8.5.4"
  autoprefixer: "^10.4.21"
  zustand: "^5.0.5"
  "react-dom": "^18.3.1"
  "react-is": "^18.3.1"
  "@types/react": "^18.3.1"
  "@types/react-dom": "^18.3.1"
  "@tanstack/react-query": ^5.59.15
  "@types/node": "^20.17.7"
  "react-hook-form": "^7.57.0"
  "@hookform/resolvers": "^5.1.1"
  eslint: "^8.35.0"
