name: Add Issue to Frontend Project

on:
  issues:
    types:
      - opened

jobs:
  track_issue:
    uses: instill-ai/meta/.github/workflows/add-issue-to-prj.yml@main
    with:
      project_number: 1 # Frontend Project
    secrets:
      botGitHubToken: ${{ secrets.botGitHubToken }}
