name: Add PR to Frontend Project

on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  track_pr:
    uses: instill-ai/meta/.github/workflows/add-pr-to-prj.yml@main
    with:
      project_number: 1 # Frontend Project
    secrets:
      botGitHubToken: ${{ secrets.botGitHubToken }}
