name: SDK Integration test

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      protobuf-branch:
        required: true
        type: string

jobs:
  run-sdk-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.1.4
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: rm -rf node_modules && pnpm i --frozen-lockfile

      - name: generate mock servers
        run: pnpm run --filter instill-sdk gen-mocks ${{ inputs.protobuf-branch }}

      - name: Run integration tests
        run: pnpm run --filter instill-sdk integration-test
